use crate::{components::detect_mobile_device, models::chatlog::{parse_think_block, Chatlog, Message}};
use sycamore::prelude::*;
use web_sys::KeyboardEvent;

/// Renders a chat message component with different styling for user and AI messages.
///
/// The component displays messages with different positioning and colors depending on whether
/// the message was generated by an AI or a user. User messages appear on the right side with
/// a blue background, while AI messages appear on the left side with a gray background.
#[component(inline_props)]
pub fn ChatMessageComponent(msg: Message) -> View {
    let show_actions = create_signal(false);
    let toggle_actions = move |_| {
        show_actions.set(!show_actions.get());
    };

    let is_editing = create_signal(false);
    let edited_message = create_signal(msg.message.clone());
    let edited_image_base64 = create_signal(msg.image_base64.clone());

    let handle_edit_done = move || {
        is_editing.set(false);

        let new_msg = edited_message.get_clone_untracked();
        if !new_msg.trim().is_empty() {
            let mut active_chatlog = use_context::<Signal<Chatlog>>().get_clone_untracked();
            active_chatlog.update_msg(msg.id, new_msg, edited_image_base64.get_clone());
            show_actions.set(false);
        }
    };

    let handle_remove_image = move || {
        edited_image_base64.set(None);
        let mut active_chatlog = use_context::<Signal<Chatlog>>().get_clone_untracked();
        active_chatlog.update_msg(msg.id, edited_message.get_clone(), None);
    };

    let handle_purge_msgs = move || {
        let confirmed =
            window().confirm_with_message("Are you sure you want to delete this message AND all older messages also?");
        if let Ok(is_ok) = confirmed {
            if is_ok {
                let mut active_chatlog = use_context::<Signal<Chatlog>>().get_clone_untracked();
                active_chatlog.purge_messages(msg.id);
            }
        }
    };

    let handle_delete_msg = move || {
        let confirmed =
            window().confirm_with_message("Are you sure you want to delete this message?");
        if let Ok(is_ok) = confirmed {
            if is_ok {
                let mut active_chatlog = use_context::<Signal<Chatlog>>().get_clone_untracked();
                active_chatlog.remove_message(msg.id);
            }
        }
    };

    let handle_regeneration = move || {
        // the remove operation is 'silent' here because otherwise
        // some behind-the-scenes stuff triggers and a call to
        // `trigger_response_generation()` will cause a crash.
        // Making it use `remove_message_silent()` has the unfortunate
        // side effect of not updating the chatlog view until the
        // new response comes in.
        let active_chatlog = use_context::<Signal<Chatlog>>();
        active_chatlog.update(|log| {
            log.remove_message_silent(msg.id);
        });

        let log = active_chatlog.get_clone();
        log.trigger_response_generation();
        show_actions.set(false);
    };

    // signal for tracking if think block is expanded, unexpanded by default
    let show_think_block = create_signal(false);

    view! {
    div (class = if !msg.ai_generated {
        "message-container-user"
    } else {
        "message-container-ai"
    }) {
        div (class = if !msg.ai_generated {
            "message-bubble-user"
        } else {
            "message-bubble-ai"
        }) {
            // Show text or input based on editing state
            div (class="message-content") {
                (if !is_editing.get() {
                    // Check for think block by setting up a msg clone with the edited content
                    // from the signal
                    let maybe_msg_has_thoughts = parse_think_block(edited_message.get_clone());

                    if let Some((main_content, think_content)) = maybe_msg_has_thoughts.clone() {
                        let markdown_content = ammonia::clean(&markdown::to_html(&main_content));
                        view! {
                            div{
                                div(class="think-block-header", on:click=move |_| {
                                    show_think_block.set(!show_think_block.get());
                                }) {
                                    "Thought Process "
                                    span(class="think-toggle") {
                                        (if show_think_block.get() { "▼" } else { "▶" })
                                    }
                                }
                                div(class=if show_think_block.get() { "think-block-content" } else { "hidden" }) {
                                    (think_content)
                                }

                                div (class="mt-4", dangerously_set_inner_html=markdown_content)
                            }
                        }
                    } else {
                        let markdown_content = ammonia::clean(&markdown::to_html(edited_message.get_clone().as_str()));

                        view! {
                            div(dangerously_set_inner_html=markdown_content)
                        }
                    }
                } else {
                    view! {
                        textarea(
                            rows = "5",
                            class = "message-content-editable block",
                            bind:value = edited_message,
                            on:blur = move |_| {
                                handle_edit_done();
                            },
                            on:keydown = move |e:KeyboardEvent| {
                                if !detect_mobile_device() {
                                    if e.key() == "Enter" && !e.shift_key() {
                                        e.prevent_default();
                                        handle_edit_done();
                                    }
                                }
                            },
                        )
                    }
                })

                (if let Some(data_url_str) = edited_image_base64.get_clone() {
                    if !is_editing.get() {
                        view! {
                            div {
                                img(src=data_url_str, alt="Image for Message", class="message-image")
                            }
                        }
                    } else {
                        view! {
                            div(class="flex flex-col items-start") {
                                div(class="relative") {
                                    img(src=data_url_str, alt="Image for Message", class="message-image")
                                    button(
                                        on:click=move |_| {
                                            handle_remove_image();
                                        },
                                        class="input-image-remove-button"
                                    ) {
                                        "X"
                                    }
                                }
                            }
                         }
                    }
                } else {
                    view! { }
                })
            }

            div(class="message-actions") {
                div(
                    class = "action-badge",
                    on:click = toggle_actions
                ) { "~"}
                div(
                    class = if show_actions.get() {
                        "actions-row"
                    } else {
                        "hidden"
                    }
                    ) {
                        button(
                            class="action-button",
                            on:click=move |_| {
                                handle_purge_msgs();
                            }
                        ) { "Purge" }
                        button(
                            class="action-button",
                            on:click=move |_| {
                                handle_delete_msg();
                            }
                        ) { "Delete" }
                        button(
                            class="action-button",
                            on:click=move |_| {
                                is_editing.set(!is_editing.get())
                            }
                        ) { "Edit" }
                        button(
                            class="action-button",
                            on:click=move |_| {
                                handle_regeneration();
                            }
                        ) { "Regenerate" }
                    }
                }
            }
        }
    }
}
